server:
  port: 9999
spring:
  application:
    name: docker-config-server
  config:
    import:
      - classpath:cloud-config-git.yml
      - classpath:local-compose-eureka.yml
      - classpath:actuator.yml
      - classpath:spring-boot-admin-client.yml
logging:
  level:
    root: debug
encrypt:
  key-store:
    type: jks
    location: EncryptedConfigServerKey.jks
    alias: EncryptedConfigServerKey
    password: asdf1234
