server:
  port: 9992
spring:
  application:
    name: foobar-user-history
  config:
    import:
      - classpath:local-compose-eureka.yml
      - classpath:actuator.yml
      - classpath:spring-boot-admin-client.yml
logging:
  level:
    root: debug
