version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
  eureka-server:
    image: chagchagchag/docker-eureka-server
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8948:8948"
    environment:
      JIB_CONTAINER_PROFILE: compose
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    networks:
      - docker-spring-cloud
  docker-config-service:
    image: chagchagchag/docker-config-server
    container_name: config-server
    hostname: config-server
    ports:
      - "9999:9999"
    environment:
      JIB_CONTAINER_PROFILE: compose
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8948/eureka/
    networks:
      - docker-spring-cloud
    links:
      - eureka-server
    depends_on:
      - eureka-server
networks:
  docker-spring-cloud:
    external: true