version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
  eureka-server:
    image: chagchagchag/docker-eureka-server
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8948:8948"
    environment:
      JIB_CONTAINER_PROFILE: compose
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    networks:
      - docker-spring-cloud
  docker-config-server:
    image: chagchagchag/docker-config-server
    container_name: config-server
    hostname: config-server
    ports:
      - "9999:9999"
    environment:
      JIB_CONTAINER_PROFILE: compose
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8948/eureka/
    networks:
      - docker-spring-cloud
    links:
      - eureka-server
    depends_on:
      - eureka-server
  docker-admin-dashboard:
    image: chagchagchag/docker-admin-dashboard
    container_name: admin-dashboard
    hostname: admin-dashboard
    ports:
      - "7776:7776"
    environment:
      JIB_CONTAINER_PROFILE: compose
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8948/eureka/
    networks:
      - docker-spring-cloud
    links:
      - eureka-server
      - docker-config-server
    depends_on:
      - eureka-server
      - docker-config-server
  docker-user-history:
    image: chagchagchag/docker-user-history
    container_name: user-history
    hostname: user-history
    ports:
      - "9992:9992"
    environment:
      JIB_CONTAINER_PROFILE: compose
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8948/eureka/
    networks:
      - docker-spring-cloud
    links:
      - eureka-server
      - docker-config-server
    depends_on:
      - eureka-server
      - docker-config-server
  docker-user-service:
    image: chagchagchag/docker-user-service
    container_name: user-service
    hostname: user-service
    ports:
      - "9991:9991"
    environment:
      JIB_CONTAINER_PROFILE: compose
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8948/eureka/
    networks:
      - docker-spring-cloud
    links:
      - eureka-server
      - docker-config-server
      - docker-user-history
    depends_on:
      - eureka-server
      - docker-config-server
networks:
  docker-spring-cloud:
    external: true