server:
  port: 9991

spring:
  application:
    name: foobar-user-service
  config:
    import:
      - classpath:local-was-eureka.yml
      - classpath:actuator.yml
      - classpath:spring-boot-admin-client.yml

logging:
  level:
    root: info
