server:
  port: 8948

spring:
  application:
    name: discovery-service
  config:
    import:
      - classpath:local-was-eureka.yml
      - classpath:actuator.yml
#      - classpath:spring-boot-admin-client.yml
