spring:
  boot:
    admin:
      client:
        # admin server 주소
        url: http://admin-dashboard:7776
        # 애플리케이션 로딩이 완료된 후 자동으로 Admin Server 에 등록
        auto-registration: true
        username: client
        password: client
        instance:
          name: eureka-server-1-8948
          # 현재 admin-client 자기 자신의 주소
          service-url: http://eureka-server:8948
          #          health-url: http://eureka-server:8948/actuator/health
          #          management-url: http://eureka-server:8948/actuator
          metadata:
            user:
              name: client
              password: client