version: '3.7'
services:
  docker-discovery-service:
    image: chagchagchag/docker-discovery-service
#    container_name: docker-discovery-service
    hostname: docker-discovery-service
    ports:
      - "8761:8761"
    environment:
      JIB_CONTAINER_PROFILE: compose
    networks:
      - docker-spring-cloud
#  docker-discovery-client:
#    image: chagchagchag/docker-discovery-client
#    environment:
#      JIB_CONTAINER_PROFILE: compose
#    networks:
#      - docker-spring-cloud
  docker-config-service:
    image: chagchagchag/docker-config-service
    container_name: docker-config-service
    hostname: docker-config-service
    ports:
      - "9999:9999"
    environment:
      JIB_CONTAINER_PROFILE: compose
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    networks:
      - docker-spring-cloud
    links:
      - docker-discovery-service
#  docker-api-gateway-service:
#    image: chagchagchag/docker-api-gateway-service
#    environment:
#      JIB_CONTAINER_PROFILE: compose
#    networks:
#      - docker-spring-cloud
networks:
  docker-spring-cloud:
    external: true