version: '3.7'
services:
  empty:
    ports:
      - "0000:0000"
  docker-discovery-service:
    image: chagchagchag/docker-discovery-service
    container_name: discovery-service
    hostname: discovery-service
    ports:
      - "9961:9961"
    environment:
      JIB_CONTAINER_PROFILE: compose
      EUREKA_INSTANCE_HOSTNAME: discovery-service
    networks:
      - docker-spring-cloud
  docker-discovery-client:
    image: chagchagchag/docker-discovery-client
    environment:
      JIB_CONTAINER_PROFILE: compose
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    ports:
      - "8989:8989"
    networks:
      - docker-spring-cloud
    links:
      - docker-discovery-service
      - docker-config-service
    depends_on:
      - docker-discovery-service
      - docker-config-service
  docker-config-service:
    image: chagchagchag/docker-config-service
    container_name: docker-config-service
    hostname: docker-config-service
    ports:
      - "9999:9999"
    environment:
      JIB_CONTAINER_PROFILE: compose
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    networks:
      - docker-spring-cloud
    links:
      - docker-discovery-service
    depends_on:
      - docker-discovery-service
#  docker-api-gateway-service:
#    image: chagchagchag/docker-api-gateway-service
#    environment:
#      JIB_CONTAINER_PROFILE: compose
#    networks:
#      - docker-spring-cloud
networks:
  docker-spring-cloud:
    external: true