eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
