name: spring cloud containers build for push event

env:
  JIB_CONTAINER_PROFILE: compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JDK 17 Setting
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Permission Setting
        run: chmod +x gradlew

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PW }}

      - name: jib build
        run: |
          ./gradlew :docker-discovery-service:clean
          ./gradlew :docker-discovery-service:jib
          ./gradlew :docker-config-service:clean
          ./gradlew :docker-config-service:jib
          ./gradlew :docker-discovery-client:clean
          ./gradlew :docker-discovery-client:jib
          ./gradlew :docker-api-gateway-service:clean
          ./gradlew :docker-api-gateway-service:jib
