name: spring cloud containers build for push event

env:
  JIB_CONTAINER_PROFILE: compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JDK 17 Setting
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Permission Setting
        run: chmod +x gradlew

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PW }}

      - name: jib build
        run: |
          ./gradlew :spring-cloud:config-server:clean
          ./gradlew :spring-cloud:config-server:jibDockerBuild
          ./gradlew :spring-cloud:config-server:jib
          ./gradlew :spring-cloud:eureka-server:clean
          ./gradlew :spring-cloud:eureka-server:jibDockerBuild
          ./gradlew :spring-cloud:eureka-server:jib
          ./gradlew :spring-cloud:admin-dashboard:clean
          ./gradlew :spring-cloud:admin-dashboard:jibDockerBuild
          ./gradlew :spring-cloud:admin-dashboard:jib
          ./gradlew :foobar-user-api:foobar-user-history:clean
          ./gradlew :foobar-user-api:foobar-user-history:jibDockerBuild
          ./gradlew :foobar-user-api:foobar-user-history:jib
          ./gradlew :foobar-user-api:foobar-user-service:clean
          ./gradlew :foobar-user-api:foobar-user-service:jibDockerBuild
          ./gradlew :foobar-user-api:foobar-user-service:jib